### PR TITLE
Define an dependency property "IsFocused" on "MultiSelectTreeViewItem"

### PR DESCRIPTION
**Pull request by bhenker**
to get or set focus on nodes

### CODE REVIEW

**Comment by dg9ngf** [comment]
Apart from using spaces in a document that has tabs everywhere..., you only add a new dependency property. Could you please explain what effect that should have if it's not used anywhere and does nothing but store data for itself? I mean that new property is not connected anywhere in the code.

**Comment by bhenker** [comment]
Sorry for the spaces. This property gives me the opportunity to put the focus of a node, for example after insertion into the tree. Using a bound property of the node I can query and set the focus.
If there's another way to put the focus on a node of the tree I have no problem with that. I only found nothing so far, and I want to do everything in the ViewModel and not in code-behind

Von: Yves Goergen [mailto:notifications@github.com]
Gesendet: Sonntag, 26. April 2015 17:51
An: dg9ngf/MultiSelectTreeView
Cc: Bernd Henker
Betreff: Re: [MultiSelectTreeView] Define an dependency property "IsFocused" on "MultiSelectTreeViewItem" (#31)


Apart from using spaces in a document that has tabs everywhere..., you only add a new dependency property. Could you please explain what effect that should have if it's not used anywhere and does nothing but store data for itself? I mean that new property is not connected anywhere in the code.

**Comment by dg9ngf** [comment]
Umm, yes, but I don't see any use in a nonfunctional property. It would be a different thing if reading or setting the property actually did anything. If I decided to set this property to `true` somewhere, what would happen? I don't see it.

There's the `MultiSelectTreeView.FocusItem` method that lets you focus any tree item. It can also bring the item into view if desired.

If you're concerned about accessing the view from the view model, maybe the [ViewCommand pattern](http://unclassified.software/source/viewcommand) is of interest to you.

**Comment by bhenker** [comment]
Thanks for the informative link. With this information, the desired change is not necessary. It can solve everything in a simple elegant way different.
How do you say: Manchmal sieht man den Wald vor lauter Bäumen nicht.

**Pull request closed without merging**
