### PR TITLE
Adding logic to clear the selection if there was non-ctrl click

### PR DESCRIPTION
**Pull request by tevert**
This behavior would be expected in most treeviews - otherwise you'd have to provide a button to explicitly clear the selection, or require the user to make an empty selection box. 

This works by checking the total distance between MouseUp and MouseDown, and clearing the selection if the distance is beneath the system tolerance for click drags (and if CTRL isn't down). 

I would imagine this doesn't require a setting to control the behavior, though I'm willing to add one if deemed necessary.

### CODE REVIEW

**Comment by dg9ngf** [comment]
Could you please explain what the problem is? I can perform Ctrl and non-Ctrl clicks on items and see exactly the same behaviour as in native/Explorer tree views. Can you provide steps to reproduce the issue, preferrably in the demo application?

PS: Your pull request seems to have formatting issues from what I see in the web viewer here. Possibly mixed tabs/spaces.

**Comment by tevert** [comment]
The behavior I would expect is: 
# Select any node(s)
# Click somewhere off in the empty space of the treeview
# The selection should clear

Currently, the only way to *clear* the selection is to make a selection box that doesn't capture any items, or use the clear button. Neither of those feels very intuitive though. I can reproduce this in the demo app no problem.

Regarding the whitespace, would you like the indentation in the form of tabs or spaces?

**Comment by dg9ngf** [comment]
For the initial report, now that you explained the issue, I understood it and agree in the solution. I've moved the code directly in the OnMouseUp method though to have the event's original position available. (I believe this is independent of the actual mouse position in the moment the event handler gets to execute.) So this part of your pull request doesn't apply anymore and can be considered solved.

Now I noticed that this PR has more changes... updating... this view is changing faster than I can understand it. Are you changing this PR or is it because I have committed things meanwhile?

**Comment by tevert** [comment]
Yeah, there were some conflicts based on experimentation I was also doing per issue #28; sorry about that. 

To clarify - you've solved the issue a different way and the change in this PR is no longer needed? 

And how often do you update the Nuget distro; will this be reflected soon? 

Thanks for everything!

**Comment by dg9ngf** [comment]
I basically took the code from your change but placed it in the parent method of the call. So yes, I did manually apply your change and this one can be closed.

This will be version 1.0.6 and if nothing comes in my way soon, it could be released to NuGet like this. I'd just like to perform a little more testing with other applications tomorrow.

**Comment by tevert** [comment]
Excellent, thanks again!

**Pull request closed without merging**
